import Head from 'next/head'
import Header from "@/components/Layout/Header";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";

export default function Landing() {
    return (
        <>
        <Head>
            <title>Lumos App</title>
            <meta name="description" content='Generated by create next app'/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="favicon.ico"/>
        </Head>
        <Header/>
        <Navbar/>
        <Footer/>
        </>
    )
}